name: Deployment LIVE

on:
  push:
    branches:
      - LIVE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install RSS-Bridge
        uses: php-actions/composer@v6
        with:
          command: create-project
          args: rss-bridge/rss-bridge public/feeds/ --no-dev

      - name: Copy bridges & config
        run: |
          cp src/bridges/*.php public/feeds/bridges/
          cp src/config/* public/feeds/

      - name: rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          path: public
          switches: -avzr
          remote_path: ${{ secrets.RSS_SSH_REMOTE_PATH_LIVE }}
          remote_host: ${{ secrets.RSS_SSH_HOST }}
          remote_user: ${{ secrets.RSS_SSH_USER }}
          remote_key: ${{ secrets.RSS_SSH_PRIVATE_KEY }}

      - name: Done
        uses: cstuder/apprise-ga@master
        with:
          title: "rss.existenz.ch LIVE deployed"
          message: "{{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
