name: Deployment LIVE

on:
  push:
    branches:
      - LIVE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install RSS-Bridge
        uses: php-actions/composer@v6
        with:
          command: create-project
          only_args: -vvv rss-bridge/rss-bridge --no-dev --prefer-dist

      - name: Show directory
        run: sudo apt-get install -y && tree ${{ github.workspace }}

      - name: Output
        run: more ${{ github.workspace }}/output.log

      # - name: Copy bridges & config
      #   run: |
      #     cp ${{ github.workspace }}/src/bridges/*.php ${{ github.workspace }}/public/feeds/bridges/
      #     cp ${{ github.workspace }}/src/config/* ${{ github.workspace }}/public/feeds/

      - name: rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          path: public/
          switches: -avzr
          remote_path: ${{ secrets.RSS_SSH_REMOTE_PATH_LIVE }}
          remote_host: ${{ secrets.RSS_SSH_HOST }}
          remote_user: ${{ secrets.RSS_SSH_USER }}
          remote_key: ${{ secrets.RSS_SSH_PRIVATE_KEY }}

      - name: Done
        uses: cstuder/apprise-ga@master
        with:
          title: "rss.existenz.ch LIVE deployed"
          message: "{{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
