name: Deployment LIVE

on:
  push:
    branches:
      - LIVE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install RSS-Bridge
        uses: php-actions/composer@v6
        with:
          command: create-project
          only_args: rss-bridge/rss-bridge public/feeds/ --no-dev --prefer-dist --ignore-platform-req=ext-intl

      - name: Copy bridges & config
        run: |
          sudo cp ${{ github.workspace }}/src/bridges/*.php ${{ github.workspace }}/public/feeds/bridges/
          sudo cp ${{ github.workspace }}/src/config/* ${{ github.workspace }}/public/feeds/

      - name: rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          path: public/
          switches: -avzr
          # Remote Pfad wird durch rrsync auf der Serverseite kontrolliert
          remote_path: /
          remote_host: ${{ secrets.RSS_SSH_HOST }}
          remote_user: ${{ secrets.RSS_SSH_USER }}
          remote_key: ${{ secrets.RSS_SSH_PRIVATE_KEY }}

      - name: Done
        uses: cstuder/apprise-ga@master
        with:
          title: "rss.existenz.ch LIVE deployed"
          message: "{{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
